<?php
namespace Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

use Codeception\TestInterface;

class Api extends \Codeception\Module
{

    public function _before(TestInterface $test)
    {
        $symfony = $this->getModule('Symfony');

        $symfony->runSymfonyConsoleCommand('doctrine:database:drop',['--if-exists'=>true, '--force'=>true]);
        $symfony->runSymfonyConsoleCommand('doctrine:database:create');
        $symfony->runSymfonyConsoleCommand('doctrine:migrations:migrate', ['--no-interaction'=>true]);

        parent::_before($test); // TODO: Change the autogenerated stub
    }
}
