version: "3.7"
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  composer:
    image: composer:latest
    volumes:
      - ./composer.json:/var/www/symfony/composer.json:delegated
      - ./composer.lock:/var/www/symfony/composer.lock:delegated
      - ./vendor:/var/www/symfony/vendor
  mysql:
    image: mysql:8
    ports:
      - '8306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: symfony-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    restart: always
  node:
    image: node:latest
    volumes:
      - ./yarn.lock:/var/www/symfony/yarn.lock:delegated
      - ./package.json:/var/www/symfony/package.json:delegated
      - ./node_modules:/var/www/symfony/node_modules
      - ./public:/var/www/symfony/public:delegated
      - ./assets:/var/www/symfony/assets:cached
      - ./webpack.config.js:/var/www/symfony/webpack.config.js
      - ./.env:/var/www/symfony/.env
  codeception:
    image: codeception/codeception
    depends_on:
      - chrome
      - php
    volumes:
    - ./:/var/www/symfony
  chrome:
    image: selenium/standalone-chrome