version: "3.7"
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  composer:
    build:
      context: ./
      dockerfile: docker/composer/Dockerfile
    volumes:
      - ./:/var/www/symfony:cached
  mysql:
    image: mysql:8
    ports:
      - '8306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: symfony-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    restart: always
  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile